<?php

class CitiesTableSeeder extends Seeder
{


    public function run()
    {

        DB::table('cities')->delete();

        $cities = array(

            array('zip_code' => '10000', 'county_id' => 21, 'name' => 'Zagreb'),
            array('zip_code' => '10010','county_id' => 21,'name' => 'Zagreb-Sloboština'),
            array('zip_code' => '10020','county_id' => 21,'name' => 'Zagreb-Novi Zagreb'),
            array('zip_code' => '10040','county_id' => 21,'name' => 'Zagreb-Dubrava'),
            array('zip_code' => '10090','county_id' => 21,'name' => 'Zagreb-Susedgrad'),
            array('zip_code' => '10110','county_id' => 21,'name' => 'Zagreb-Trešnjevka'),
            array('zip_code' => '10250','county_id' => 21,'name' => 'Lučko'),
            array('zip_code' => '10251','county_id' => 21,'name' => 'Hrvatski Leskovac'),
            array('zip_code' => '10253','county_id' => 21,'name' => 'Donji Dragonožec'),
            array('zip_code' => '10255','county_id' => 1,'name' => 'Gornji Stupnik'),
            array('zip_code' => '10257','county_id' => 21,'name' => 'Brezovica'),
            array('zip_code' => '10290','county_id' => 21,'name' => 'Zaprešić'),
            array('zip_code' => '10291','county_id' => 1,'name' => 'Prigorje Brdovečko'),
            array('zip_code' => '10292','county_id' => 1,'name' => 'Šenkovec'),
            array('zip_code' => '10293','county_id' => 1,'name' => 'Dubravica'),
            array('zip_code' => '10294','county_id' => 1,'name' => 'Donja Pušća'),
            array('zip_code' => '10295','county_id' => 1,'name' => 'Kupljenovo'),
            array('zip_code' => '10296','county_id' => 1,'name' => 'Luka'),
            array('zip_code' => '10297','county_id' => 1,'name' => 'Jakovlje'),
            array('zip_code' => '10298','county_id' => 1,'name' => 'Donja Bistra'),
            array('zip_code' => '10299','county_id' => 1,'name' => 'Marija Gorica'),
            array('zip_code' => '10310','county_id' => 1,'name' => 'Ivanić-Grad'),
            array('zip_code' => '10311','county_id' => 1,'name' => 'Posavski Bregi'),
            array('zip_code' => '10312','county_id' => 1,'name' => 'Kloštar Ivanić'),
            array('zip_code' => '10313','county_id' => 1,'name' => 'Graberje Ivaničko'),
            array('zip_code' => '10314','county_id' => 1,'name' => 'Križ'),
            array('zip_code' => '10315','county_id' => 1,'name' => 'Novoselec'),
            array('zip_code' => '10316','county_id' => 1,'name' => 'Lijevi Dubrovčak'),
            array('zip_code' => '10340','county_id' => 1,'name' => 'Vrbovec'),
            array('zip_code' => '10341','county_id' => 1,'name' => 'Lonjica'),
            array('zip_code' => '10342','county_id' => 1,'name' => 'Dubrava'),
            array('zip_code' => '10343','county_id' => 1,'name' => 'Nova Kapela'),
            array('zip_code' => '10344','county_id' => 1,'name' => 'Farkaševac'),
            array('zip_code' => '10345','county_id' => 1,'name' => 'Gradec'),
            array('zip_code' => '10346','county_id' => 1,'name' => 'Preseka'),
            array('zip_code' => '10347','county_id' => 1,'name' => 'Rakovec'),
            array('zip_code' => '10360','county_id' => 21,'name' => 'Sesvete'),
            array('zip_code' => '10361','county_id' => 21,'name' => 'Sesvete-Kraljevec'),
            array('zip_code' => '10362','county_id' => 21,'name' => 'Kašina'),
            array('zip_code' => '10363','county_id' => 21,'name' => 'Belovar'),
            array('zip_code' => '10370','county_id' => 1,'name' => 'Dugo Selo'),
            array('zip_code' => '10372','county_id' => 1,'name' => 'Oborovo'),
            array('zip_code' => '10373','county_id' => 21,'name' => 'Ivanja Reka'),
            array('zip_code' => '10380','county_id' => 1,'name' => 'Sveti Ivan Zelina'),
            array('zip_code' => '10381','county_id' => 1,'name' => 'Bedenica'),
            array('zip_code' => '10382','county_id' => 1,'name' => 'Donja Zelina'),
            array('zip_code' => '10383','county_id' => 1,'name' => 'Komin'),
            array('zip_code' => '10408','county_id' => 1,'name' => 'Velika Mlaka'),
            array('zip_code' => '10410','county_id' => 1,'name' => 'Velika Gorica'),
            array('zip_code' => '10411','county_id' => 1,'name' => 'Orle'),
            array('zip_code' => '10412','county_id' => 1,'name' => 'Donja Lomnica'),
            array('zip_code' => '10413','county_id' => 1,'name' => 'Kravarsko'),
            array('zip_code' => '10414','county_id' => 1,'name' => 'Pokupsko'),
            array('zip_code' => '10415','county_id' => 1,'name' => 'Novo Čiče'),
            array('zip_code' => '10417','county_id' => 1,'name' => 'Buševec'),
            array('zip_code' => '10418','county_id' => 1,'name' => 'Dubranec'),
            array('zip_code' => '10419','county_id' => 1,'name' => 'Vukovina'),
            array('zip_code' => '10430','county_id' => 1,'name' => 'Samobor'),
            array('zip_code' => '10431','county_id' => 1,'name' => 'Sveta Nedjelja'),
            array('zip_code' => '10432','county_id' => 1,'name' => 'Bregana'),
            array('zip_code' => '10434','county_id' => 1,'name' => 'Strmec Samoborski'),
            array('zip_code' => '10435','county_id' => 1,'name' => 'Sveti Martin pod Okićem'),
            array('zip_code' => '10436','county_id' => 1,'name' => 'Rakov Potok'),
            array('zip_code' => '10437','county_id' => 1,'name' => 'Bestovje'),
            array('zip_code' => '10450','county_id' => 1,'name' => 'Jastrebarsko'),
            array('zip_code' => '10451','county_id' => 1,'name' => 'Pisarovina'),
            array('zip_code' => '10453','county_id' => 1,'name' => 'Gorica Svetojanska'),
            array('zip_code' => '10454','county_id' => 1,'name' => 'Krašić'),
            array('zip_code' => '10455','county_id' => 1,'name' => 'Kostanjevac'),
            array('zip_code' => '10456','county_id' => 1,'name' => 'Kalje'),
            array('zip_code' => '10457','county_id' => 1,'name' => 'Sošice'),
            array('zip_code' => '20000','county_id' => 19,'name' => 'Dubrovnik'),
            array('zip_code' => '20205','county_id' => 19,'name' => 'Topolo'),
            array('zip_code' => '20207','county_id' => 19,'name' => 'Mlini'),
            array('zip_code' => '20210','county_id' => 19,'name' => 'Cavtat'),
            array('zip_code' => '20213','county_id' => 19,'name' => 'Čilipi'),
            array('zip_code' => '20215','county_id' => 19,'name' => 'Gruda'),
            array('zip_code' => '20216','county_id' => 19,'name' => 'Dubravka'),
            array('zip_code' => '20217','county_id' => 19,'name' => 'Pridvorje'),
            array('zip_code' => '20218','county_id' => 19,'name' => 'Pločice'),
            array('zip_code' => '20221','county_id' => 19,'name' => 'Koločep'),
            array('zip_code' => '20222','county_id' => 19,'name' => 'Lopud'),
            array('zip_code' => '20223','county_id' => 19,'name' => 'Šipanjska Luka'),
            array('zip_code' => '20224','county_id' => 19,'name' => 'Maranovići'),
            array('zip_code' => '20225','county_id' => 19,'name' => 'Babino Polje'),
            array('zip_code' => '20226','county_id' => 19,'name' => 'Goveđari'),
            array('zip_code' => '20230','county_id' => 19,'name' => 'Ston'),
            array('zip_code' => '20231','county_id' => 19,'name' => 'Doli'),
            array('zip_code' => '20232','county_id' => 19,'name' => 'Slano'),
            array('zip_code' => '20233','county_id' => 19,'name' => 'Trsteno'),
            array('zip_code' => '20234','county_id' => 19,'name' => 'Orašac'),
            array('zip_code' => '20235','county_id' => 19,'name' => 'Zaton Veliki'),
            array('zip_code' => '20236','county_id' => 19,'name' => 'Mokošica'),
            array('zip_code' => '20240','county_id' => 19,'name' => 'Trpanj'),
            array('zip_code' => '20242','county_id' => 19,'name' => 'Oskorušno'),
            array('zip_code' => '20243','county_id' => 19,'name' => 'Kuna'),
            array('zip_code' => '20244','county_id' => 19,'name' => 'Potomje'),
            array('zip_code' => '20245','county_id' => 19,'name' => 'Trstenik'),
            array('zip_code' => '20246','county_id' => 19,'name' => 'Janjina'),
            array('zip_code' => '20247','county_id' => 19,'name' => 'Žuljana'),
            array('zip_code' => '20248','county_id' => 19,'name' => 'Putniković'),
            array('zip_code' => '20250','county_id' => 19,'name' => 'Orebić'),
            array('zip_code' => '20260','county_id' => 19,'name' => 'Korčula'),
            array('zip_code' => '20263','county_id' => 19,'name' => 'Lumbarda'),
            array('zip_code' => '20264','county_id' => 19,'name' => 'Račišće'),
            array('zip_code' => '20267','county_id' => 19,'name' => 'Kućište'),
            array('zip_code' => '20269','county_id' => 19,'name' => 'Lovište'),
            array('zip_code' => '20270','county_id' => 19,'name' => 'Vela Luka'),
            array('zip_code' => '20271','county_id' => 19,'name' => 'Blato'),
            array('zip_code' => '20272','county_id' => 19,'name' => 'Smokvica'),
            array('zip_code' => '20273','county_id' => 19,'name' => 'Čara'),
            array('zip_code' => '20274','county_id' => 19,'name' => 'Pupnat'),
            array('zip_code' => '20275','county_id' => 19,'name' => 'Žrnovo'),
            array('zip_code' => '20278','county_id' => 19,'name' => 'Nova Sela'),
            array('zip_code' => '20290','county_id' => 19,'name' => 'Lastovo'),
            array('zip_code' => '20340','county_id' => 19,'name' => 'Ploče'),
            array('zip_code' => '20341','county_id' => 19,'name' => 'Kula Norinska'),
            array('zip_code' => '20342','county_id' => 19,'name' => 'Otrić Seoci'),
            array('zip_code' => '20343','county_id' => 19,'name' => 'Rogotin'),
            array('zip_code' => '20344','county_id' => 19,'name' => 'Komin (Dalma)'),
            array('zip_code' => '20345','county_id' => 19,'name' => 'Staševica'),
            array('zip_code' => '20350','county_id' => 19,'name' => 'Metković'),
            array('zip_code' => '20352','county_id' => 19,'name' => 'Vid'),
            array('zip_code' => '20353','county_id' => 19,'name' => 'Mlinište'),
            array('zip_code' => '20355','county_id' => 19,'name' => 'Opuzen'),
            array('zip_code' => '20356','county_id' => 19,'name' => 'Klek'),
            array('zip_code' => '20357','county_id' => 19,'name' => 'Blace'),
            array('zip_code' => '21000','county_id' => 17,'name' => 'Split'),
            array('zip_code' => '21201','county_id' => 17,'name' => 'Prgomet'),
            array('zip_code' => '21202','county_id' => 17,'name' => 'Lećevica'),
            array('zip_code' => '21203','county_id' => 17,'name' => 'Donji Muć'),
            array('zip_code' => '21204','county_id' => 17,'name' => 'Dugopolje'),
            array('zip_code' => '21205','county_id' => 17,'name' => 'Donji Dolac'),
            array('zip_code' => '21206','county_id' => 17,'name' => 'Donje Ogorje'),
            array('zip_code' => '21207','county_id' => 17,'name' => 'Kostanje'),
            array('zip_code' => '21208','county_id' => 17,'name' => 'Kučiće'),
            array('zip_code' => '21209','county_id' => 17,'name' => 'Mravince'),
            array('zip_code' => '21210','county_id' => 17,'name' => 'Solin'),
            array('zip_code' => '21212','county_id' => 17,'name' => 'Kaštel Sućurac'),
            array('zip_code' => '21213','county_id' => 17,'name' => 'Kaštel Gomilica'),
            array('zip_code' => '21214','county_id' => 17,'name' => 'Kaštel Kambelovac'),
            array('zip_code' => '21215','county_id' => 17,'name' => 'Kaštel Lukšić'),
            array('zip_code' => '21216','county_id' => 17,'name' => 'Kaštel Stari'),
            array('zip_code' => '21217','county_id' => 17,'name' => 'Kaštel Štafilić'),
            array('zip_code' => '21220','county_id' => 17,'name' => 'Trogir'),
            array('zip_code' => '21222','county_id' => 17,'name' => 'Marina'),
            array('zip_code' => '21223','county_id' => 17,'name' => 'Okrug Gornji'),
            array('zip_code' => '21224','county_id' => 17,'name' => 'Slatine'),
            array('zip_code' => '21225','county_id' => 17,'name' => 'Drvenik Veliki'),
            array('zip_code' => '21226','county_id' => 17,'name' => 'Vinišće'),
            array('zip_code' => '21227','county_id' => 17,'name' => 'Primorski Dolac'),
            array('zip_code' => '21228','county_id' => 17,'name' => 'Blizna Donja'),
            array('zip_code' => '21229','county_id' => 17,'name' => 'Crivac'),
            array('zip_code' => '21230','county_id' => 17,'name' => 'Sinj'),
            array('zip_code' => '21231','county_id' => 17,'name' => 'Klis'),
            array('zip_code' => '21232','county_id' => 17,'name' => 'Dicmo'),
            array('zip_code' => '21233','county_id' => 17,'name' => 'Hrvace'),
            array('zip_code' => '21236','county_id' => 17,'name' => 'Vrlika'),
            array('zip_code' => '21238','county_id' => 17,'name' => 'Otok (Dalmacija)'),
            array('zip_code' => '21240','county_id' => 17,'name' => 'Trilj'),
            array('zip_code' => '21241','county_id' => 17,'name' => 'Obrovac Sinjski'),
            array('zip_code' => '21242','county_id' => 17,'name' => 'Grab'),
            array('zip_code' => '21243','county_id' => 17,'name' => 'Ugljane'),
            array('zip_code' => '21244','county_id' => 17,'name' => 'Cista Velika'),
            array('zip_code' => '21245','county_id' => 17,'name' => 'Tijarica'),
            array('zip_code' => '21246','county_id' => 17,'name' => 'Aržano'),
            array('zip_code' => '21247','county_id' => 17,'name' => 'Neorić'),
            array('zip_code' => '21250','county_id' => 17,'name' => 'Šestanovac'),
            array('zip_code' => '21251','county_id' => 17,'name' => 'Žrnovnica'),
            array('zip_code' => '21252','county_id' => 17,'name' => 'Tugare'),
            array('zip_code' => '21253','county_id' => 17,'name' => 'Gata'),
            array('zip_code' => '21254','county_id' => 17,'name' => 'Blato na Cetini'),
            array('zip_code' => '21255','county_id' => 17,'name' => 'Zadvarje'),
            array('zip_code' => '21256','county_id' => 17,'name' => 'Cista Provo'),
            array('zip_code' => '21257','county_id' => 17,'name' => 'Lovreć'),
            array('zip_code' => '21260','county_id' => 17,'name' => 'Imotski'),
            array('zip_code' => '21261','county_id' => 17,'name' => 'Runović'),
            array('zip_code' => '21262','county_id' => 17,'name' => 'Kamenmost'),
            array('zip_code' => '21263','county_id' => 17,'name' => 'Krivodol'),
            array('zip_code' => '21264','county_id' => 17,'name' => 'Donji Proložac'),
            array('zip_code' => '21265','county_id' => 17,'name' => 'Studenci'),
            array('zip_code' => '21266','county_id' => 17,'name' => 'Zmijavci'),
            array('zip_code' => '21267','county_id' => 17,'name' => 'Ričice'),
            array('zip_code' => '21270','county_id' => 17,'name' => 'Zagvozd'),
            array('zip_code' => '21271','county_id' => 17,'name' => 'Grabovac'),
            array('zip_code' => '21272','county_id' => 17,'name' => 'Slivno'),
            array('zip_code' => '21273','county_id' => 17,'name' => 'Župa'),
            array('zip_code' => '21275','county_id' => 17,'name' => 'Dragljane'),
            array('zip_code' => '21276','county_id' => 17,'name' => 'Vrgorac'),
            array('zip_code' => '21277','county_id' => 17,'name' => 'Veliki Prolog'),
            array('zip_code' => '21292','county_id' => 17,'name' => 'Srinjine'),
            array('zip_code' => '21300','county_id' => 17,'name' => 'Makarska'),
            array('zip_code' => '21310','county_id' => 17,'name' => 'Omiš'),
            array('zip_code' => '21311','county_id' => 17,'name' => 'Stobreč'),
            array('zip_code' => '21312','county_id' => 17,'name' => 'Podstrana'),
            array('zip_code' => '21314','county_id' => 17,'name' => 'Jesenice'),
            array('zip_code' => '21315','county_id' => 17,'name' => 'Dugi Rat'),
            array('zip_code' => '21317','county_id' => 17,'name' => 'Lokva Rogoznica'),
            array('zip_code' => '21318','county_id' => 17,'name' => 'Mimice'),
            array('zip_code' => '21320','county_id' => 17,'name' => 'Baška Voda'),
            array('zip_code' => '21322','county_id' => 17,'name' => 'Brela'),
            array('zip_code' => '21323','county_id' => 17,'name' => 'Promajna'),
            array('zip_code' => '21325','county_id' => 17,'name' => 'Tučepi'),
            array('zip_code' => '21327','county_id' => 17,'name' => 'Podgora'),
            array('zip_code' => '21328','county_id' => 17,'name' => 'Drašnice'),
            array('zip_code' => '21329','county_id' => 17,'name' => 'Igrane'),
            array('zip_code' => '21330','county_id' => 17,'name' => 'Gradac'),
            array('zip_code' => '21333','county_id' => 17,'name' => 'Drvenik'),
            array('zip_code' => '21334','county_id' => 17,'name' => 'Zaostrog'),
            array('zip_code' => '21335','county_id' => 17,'name' => 'Podaca'),
            array('zip_code' => '21400','county_id' => 17,'name' => 'Supetar'),
            array('zip_code' => '21403','county_id' => 17,'name' => 'Sutivan'),
            array('zip_code' => '21404','county_id' => 17,'name' => 'Ložišća'),
            array('zip_code' => '21405','county_id' => 17,'name' => 'Milna'),
            array('zip_code' => '21410','county_id' => 17,'name' => 'Postira'),
            array('zip_code' => '21412','county_id' => 17,'name' => 'Pučišća'),
            array('zip_code' => '21413','county_id' => 17,'name' => 'Povlja'),
            array('zip_code' => '21420','county_id' => 17,'name' => 'Bol'),
            array('zip_code' => '21423','county_id' => 17,'name' => 'Nerežišća'),
            array('zip_code' => '21424','county_id' => 17,'name' => 'Pražnica'),
            array('zip_code' => '21425','county_id' => 17,'name' => 'Selca'),
            array('zip_code' => '21430','county_id' => 17,'name' => 'Grohote'),
            array('zip_code' => '21432','county_id' => 17,'name' => 'Stomorska'),
            array('zip_code' => '21450','county_id' => 17,'name' => 'Hvar'),
            array('zip_code' => '21454','county_id' => 17,'name' => 'Brusje'),
            array('zip_code' => '21460','county_id' => 17,'name' => 'Stari Grad'),
            array('zip_code' => '21462','county_id' => 17,'name' => 'Vrbanj'),
            array('zip_code' => '21463','county_id' => 17,'name' => 'Vrboska'),
            array('zip_code' => '21465','county_id' => 17,'name' => 'Jelsa'),
            array('zip_code' => '21466','county_id' => 17,'name' => 'Zastražišće'),
            array('zip_code' => '21467','county_id' => 17,'name' => 'Gdinj'),
            array('zip_code' => '21469','county_id' => 17,'name' => 'Sućuraj'),
            array('zip_code' => '21480','county_id' => 17,'name' => 'Vis'),
            array('zip_code' => '21483','county_id' => 17,'name' => 'Podšpilje'),
            array('zip_code' => '21485','county_id' => 17,'name' => 'Komiža'),
            array('zip_code' => '22000','county_id' => 15,'name' => 'Šibenik'),
            array('zip_code' => '22030','county_id' => 15,'name' => 'Šibenik-Zablaće'),
            array('zip_code' => '22202','county_id' => 15,'name' => 'Primošten'),
            array('zip_code' => '22203','county_id' => 15,'name' => 'Rogoznica'),
            array('zip_code' => '22204','county_id' => 15,'name' => 'Široke'),
            array('zip_code' => '22205','county_id' => 15,'name' => 'Perković'),
            array('zip_code' => '22206','county_id' => 15,'name' => 'Boraja'),
            array('zip_code' => '22211','county_id' => 15,'name' => 'Vodice'),
            array('zip_code' => '22212','county_id' => 15,'name' => 'Tribunj'),
            array('zip_code' => '22213','county_id' => 15,'name' => 'Pirovac'),
            array('zip_code' => '22214','county_id' => 15,'name' => 'Čista Velika'),
            array('zip_code' => '22215','county_id' => 15,'name' => 'Zaton'),
            array('zip_code' => '22221','county_id' => 15,'name' => 'Lozovac'),
            array('zip_code' => '22222','county_id' => 15,'name' => 'Skradin'),
            array('zip_code' => '22232','county_id' => 15,'name' => 'Zlarin'),
            array('zip_code' => '22233','county_id' => 15,'name' => 'Prvić Luka'),
            array('zip_code' => '22234','county_id' => 15,'name' => 'Prvić Šepurine'),
            array('zip_code' => '22235','county_id' => 15,'name' => 'Kaprije'),
            array('zip_code' => '22236','county_id' => 15,'name' => 'Žirje'),
            array('zip_code' => '22240','county_id' => 15,'name' => 'Tisno'),
            array('zip_code' => '22242','county_id' => 15,'name' => 'Jezera'),
            array('zip_code' => '22243','county_id' => 15,'name' => 'Murter'),
            array('zip_code' => '22244','county_id' => 15,'name' => 'Betina'),
            array('zip_code' => '22300','county_id' => 15,'name' => 'Knin'),
            array('zip_code' => '22301','county_id' => 15,'name' => 'Golubić'),
            array('zip_code' => '22303','county_id' => 15,'name' => 'Oklaj'),
            array('zip_code' => '22305','county_id' => 15,'name' => 'Kistanje'),
            array('zip_code' => '22310','county_id' => 15,'name' => 'Kijevo'),
            array('zip_code' => '22320','county_id' => 15,'name' => 'Drniš'),
            array('zip_code' => '22321','county_id' => 15,'name' => 'Siverić'),
            array('zip_code' => '22322','county_id' => 15,'name' => 'Ružić'),
            array('zip_code' => '22323','county_id' => 15,'name' => 'Unešić'),
            array('zip_code' => '22324','county_id' => 15,'name' => 'Drinovci'),
            array('zip_code' => '23000','county_id' => 13,'name' => 'Zadar'),
            array('zip_code' => '23205','county_id' => 13,'name' => 'Bibinje'),
            array('zip_code' => '23206','county_id' => 13,'name' => 'Sukošan'),
            array('zip_code' => '23207','county_id' => 13,'name' => 'Sveti Filip i Jakov'),
            array('zip_code' => '23210','county_id' => 13,'name' => 'Biograd na moru'),
            array('zip_code' => '23211','county_id' => 13,'name' => 'Pakoštane'),
            array('zip_code' => '23212','county_id' => 13,'name' => 'Tkon'),
            array('zip_code' => '23222','county_id' => 13,'name' => 'Zemunik'),
            array('zip_code' => '23223','county_id' => 13,'name' => 'Škabrnja'),
            array('zip_code' => '23226','county_id' => 13,'name' => 'Pridraga'),
            array('zip_code' => '23231','county_id' => 13,'name' => 'Petrčane'),
            array('zip_code' => '23232','county_id' => 13,'name' => 'Nin'),
            array('zip_code' => '23233','county_id' => 13,'name' => 'Privlaka (Dalmacija)'),
            array('zip_code' => '23234','county_id' => 13,'name' => 'Vir'),
            array('zip_code' => '23235','county_id' => 13,'name' => 'Vrsi'),
            array('zip_code' => '23241','county_id' => 13,'name' => 'Poličnik'),
            array('zip_code' => '23242','county_id' => 13,'name' => 'Posedarje'),
            array('zip_code' => '23243','county_id' => 13,'name' => 'Jasenice'),
            array('zip_code' => '23244','county_id' => 13,'name' => 'Starigrad Paklenica'),
            array('zip_code' => '23245','county_id' => 13,'name' => 'Tribanj'),
            array('zip_code' => '23247','county_id' => 13,'name' => 'Vinjerac'),
            array('zip_code' => '23248','county_id' => 13,'name' => 'Ražanac'),
            array('zip_code' => '23249','county_id' => 13,'name' => 'Povljana'),
            array('zip_code' => '23250','county_id' => 13,'name' => 'Pag'),
            array('zip_code' => '23251','county_id' => 13,'name' => 'Kolan'),
            array('zip_code' => '23262','county_id' => 13,'name' => 'Pašman'),
            array('zip_code' => '23263','county_id' => 13,'name' => 'Ždrelac'),
            array('zip_code' => '23264','county_id' => 13,'name' => 'Neviđane'),
            array('zip_code' => '23271','county_id' => 13,'name' => 'Kukljica'),
            array('zip_code' => '23272','county_id' => 13,'name' => 'Kali'),
            array('zip_code' => '23273','county_id' => 13,'name' => 'Preko'),
            array('zip_code' => '23274','county_id' => 13,'name' => 'Lukoran'),
            array('zip_code' => '23275','county_id' => 13,'name' => 'Ugljan'),
            array('zip_code' => '23281','county_id' => 13,'name' => 'Sali'),
            array('zip_code' => '23282','county_id' => 13,'name' => 'Žman'),
            array('zip_code' => '23283','county_id' => 13,'name' => 'Rava'),
            array('zip_code' => '23284','county_id' => 13,'name' => 'Veli Iž'),
            array('zip_code' => '23285','county_id' => 13,'name' => 'Brbinj'),
            array('zip_code' => '23286','county_id' => 13,'name' => 'Božava'),
            array('zip_code' => '23287','county_id' => 13,'name' => 'Veli Rat'),
            array('zip_code' => '23291','county_id' => 13,'name' => 'Sestrunj'),
            array('zip_code' => '23292','county_id' => 13,'name' => 'Molat'),
            array('zip_code' => '23293','county_id' => 13,'name' => 'Ist'),
            array('zip_code' => '23294','county_id' => 13,'name' => 'Premuda'),
            array('zip_code' => '23295','county_id' => 13,'name' => 'Silba'),
            array('zip_code' => '23296','county_id' => 13,'name' => 'Olib'),
            array('zip_code' => '23312','county_id' => 13,'name' => 'Novigrad (Dalmacija)'),
            array('zip_code' => '23420','county_id' => 13,'name' => 'Benkovac'),
            array('zip_code' => '23422','county_id' => 13,'name' => 'Stankovci'),
            array('zip_code' => '23423','county_id' => 13,'name' => 'Polača'),
            array('zip_code' => '23440','county_id' => 13,'name' => 'Gračac'),
            array('zip_code' => '23445','county_id' => 13,'name' => 'Srb'),
            array('zip_code' => '23450','county_id' => 13,'name' => 'Obrovac'),
            array('zip_code' => '23452','county_id' => 13,'name' => 'Karin'),
            array('zip_code' => '31000','county_id' => 14,'name' => 'Osijek'),
            array('zip_code' => '31204','county_id' => 14,'name' => 'Bijelo Brdo'),
            array('zip_code' => '31205','county_id' => 14,'name' => 'Aljmaš'),
            array('zip_code' => '31206','county_id' => 14,'name' => 'Erdut'),
            array('zip_code' => '31207','county_id' => 14,'name' => 'Tenja'),
            array('zip_code' => '31208','county_id' => 14,'name' => 'Petrijevci'),
            array('zip_code' => '31214','county_id' => 14,'name' => 'Laslovo (Szentlászló)'),
            array('zip_code' => '31215','county_id' => 14,'name' => 'Ernestinovo'),
            array('zip_code' => '31216','county_id' => 14,'name' => 'Antunovac'),
            array('zip_code' => '31220','county_id' => 14,'name' => 'Višnjevac'),
            array('zip_code' => '31221','county_id' => 14,'name' => 'Josipovac'),
            array('zip_code' => '31222','county_id' => 14,'name' => 'Bizovac'),
            array('zip_code' => '31223','county_id' => 14,'name' => 'Brođanci'),
            array('zip_code' => '31224','county_id' => 14,'name' => 'Koška'),
            array('zip_code' => '31225','county_id' => 14,'name' => 'Breznica Našička'),
            array('zip_code' => '31226','county_id' => 14,'name' => 'Dalj'),
            array('zip_code' => '31227','county_id' => 14,'name' => 'Zelčin'),
            array('zip_code' => '31300','county_id' => 14,'name' => 'Beli Manastir'),
            array('zip_code' => '31301','county_id' => 14,'name' => 'Branjin Vrh'),
            array('zip_code' => '31302','county_id' => 14,'name' => 'Kneževo'),
            array('zip_code' => '31303','county_id' => 14,'name' => 'Popovac'),
            array('zip_code' => '31304','county_id' => 14,'name' => 'Duboševica'),
            array('zip_code' => '31305','county_id' => 14,'name' => 'Draž'),
            array('zip_code' => '31306','county_id' => 14,'name' => 'Batina'),
            array('zip_code' => '31307','county_id' => 14,'name' => 'Zmajevac (Vörösmart)'),
            array('zip_code' => '31308','county_id' => 14,'name' => 'Suza (Csúza)'),
            array('zip_code' => '31309','county_id' => 14,'name' => 'Kneževi Vinogradi'),
            array('zip_code' => '31315','county_id' => 14,'name' => 'Karanac'),
            array('zip_code' => '31321','county_id' => 14,'name' => 'Petlovac'),
            array('zip_code' => '31322','county_id' => 14,'name' => 'Baranjsko Petrovo Selo'),
            array('zip_code' => '31323','county_id' => 14,'name' => 'Bolman'),
            array('zip_code' => '31324','county_id' => 14,'name' => 'Jagodnjak'),
            array('zip_code' => '31325','county_id' => 14,'name' => 'Čeminac'),
            array('zip_code' => '31326','county_id' => 14,'name' => 'Darda'),
            array('zip_code' => '31327','county_id' => 14,'name' => 'Bilje'),
            array('zip_code' => '31328','county_id' => 14,'name' => 'Lug (Laskó)'),
            array('zip_code' => '31400','county_id' => 14,'name' => 'Đakovo'),
            array('zip_code' => '31401','county_id' => 14,'name' => 'Viškovci'),
            array('zip_code' => '31402','county_id' => 14,'name' => 'Semeljci'),
            array('zip_code' => '31403','county_id' => 14,'name' => 'Vuka'),
            array('zip_code' => '31404','county_id' => 14,'name' => 'Vladislavci'),
            array('zip_code' => '31410','county_id' => 14,'name' => 'Strizivojna'),
            array('zip_code' => '31411','county_id' => 14,'name' => 'Trnava'),
            array('zip_code' => '31415','county_id' => 14,'name' => 'Selci Đakovački'),
            array('zip_code' => '31416','county_id' => 14,'name' => 'Levanjska Varoš'),
            array('zip_code' => '31417','county_id' => 14,'name' => 'Piškorevci'),
            array('zip_code' => '31418','county_id' => 14,'name' => 'Drenje'),
            array('zip_code' => '31421','county_id' => 14,'name' => 'Satnica Đakovačka'),
            array('zip_code' => '31422','county_id' => 14,'name' => 'Gorjani'),
            array('zip_code' => '31423','county_id' => 14,'name' => 'Bračevci'),
            array('zip_code' => '31424','county_id' => 14,'name' => 'Punitovci'),
            array('zip_code' => '31431','county_id' => 14,'name' => 'Čepin'),
            array('zip_code' => '31432','county_id' => 14,'name' => 'Budimci'),
            array('zip_code' => '31433','county_id' => 14,'name' => 'Podgorač'),
            array('zip_code' => '31500','county_id' => 14,'name' => 'Našice'),
            array('zip_code' => '31511','county_id' => 14,'name' => 'Đurđenovac'),
            array('zip_code' => '31512','county_id' => 14,'name' => 'Feričanci'),
            array('zip_code' => '31513','county_id' => 14,'name' => 'Donja Motičina'),
            array('zip_code' => '31530','county_id' => 14,'name' => 'Podravska Moslavina'),
            array('zip_code' => '31531','county_id' => 14,'name' => 'Viljevo'),
            array('zip_code' => '31540','county_id' => 14,'name' => 'Donji Miholjac'),
            array('zip_code' => '31542','county_id' => 14,'name' => 'Magadenovac'),
            array('zip_code' => '31543','county_id' => 14,'name' => 'Miholjački Poreč'),
            array('zip_code' => '31550','county_id' => 14,'name' => 'Valpovo'),
            array('zip_code' => '31551','county_id' => 14,'name' => 'Belišće'),
            array('zip_code' => '31552','county_id' => 14,'name' => 'Podgajci Podravski'),
            array('zip_code' => '31553','county_id' => 14,'name' => 'Črnkovci'),
            array('zip_code' => '31554','county_id' => 14,'name' => 'Gat'),
            array('zip_code' => '31555','county_id' => 14,'name' => 'Marijanci'),
            array('zip_code' => '32000','county_id' => 16,'name' => 'Vukovar'),
            array('zip_code' => '32010','county_id' => 16,'name' => 'Vukovar - Lipovača'),
            array('zip_code' => '32100','county_id' => 16,'name' => 'Vinkovci'),
            array('zip_code' => '32211','county_id' => 16,'name' => 'Ostrovo'),
            array('zip_code' => '32212','county_id' => 16,'name' => 'Gaboš'),
            array('zip_code' => '32213','county_id' => 16,'name' => 'Markušica'),
            array('zip_code' => '32214','county_id' => 16,'name' => 'Tordinci'),
            array('zip_code' => '32221','county_id' => 16,'name' => 'Nuštar'),
            array('zip_code' => '32222','county_id' => 16,'name' => 'Bršadin'),
            array('zip_code' => '32224','county_id' => 16,'name' => 'Trpinja'),
            array('zip_code' => '32225','county_id' => 16,'name' => 'Bobota'),
            array('zip_code' => '32227','county_id' => 16,'name' => 'Borovo'),
            array('zip_code' => '32229','county_id' => 16,'name' => 'Petrovci'),
            array('zip_code' => '32232','county_id' => 16,'name' => 'Sotin'),
            array('zip_code' => '32233','county_id' => 16,'name' => 'Opatovac'),
            array('zip_code' => '32234','county_id' => 16,'name' => 'Šarengrad'),
            array('zip_code' => '32235','county_id' => 16,'name' => 'Bapska'),
            array('zip_code' => '32236','county_id' => 16,'name' => 'Ilok'),
            array('zip_code' => '32237','county_id' => 16,'name' => 'Lovas'),
            array('zip_code' => '32238','county_id' => 16,'name' => 'Čakovci'),
            array('zip_code' => '32239','county_id' => 16,'name' => 'Negoslavci'),
            array('zip_code' => '32241','county_id' => 16,'name' => 'Stari Jankovci'),
            array('zip_code' => '32242','county_id' => 16,'name' => 'Slakovci'),
            array('zip_code' => '32243','county_id' => 16,'name' => 'Orolik'),
            array('zip_code' => '32244','county_id' => 16,'name' => 'Đeletovci'),
            array('zip_code' => '32245','county_id' => 16,'name' => 'Nijemci'),
            array('zip_code' => '32246','county_id' => 16,'name' => 'Lipovac'),
            array('zip_code' => '32247','county_id' => 16,'name' => 'Banovci'),
            array('zip_code' => '32248','county_id' => 16,'name' => 'Ilača'),
            array('zip_code' => '32249','county_id' => 16,'name' => 'Tovarnik'),
            array('zip_code' => '32251','county_id' => 16,'name' => 'Privlaka'),
            array('zip_code' => '32252','county_id' => 16,'name' => 'Otok'),
            array('zip_code' => '32253','county_id' => 16,'name' => 'Komletinci'),
            array('zip_code' => '32254','county_id' => 16,'name' => 'Vrbanja'),
            array('zip_code' => '32255','county_id' => 16,'name' => 'Soljani'),
            array('zip_code' => '32256','county_id' => 16,'name' => 'Strošinci'),
            array('zip_code' => '32257','county_id' => 16,'name' => 'Drenovci'),
            array('zip_code' => '32258','county_id' => 16,'name' => 'Posavski Podgajci'),
            array('zip_code' => '32260','county_id' => 16,'name' => 'Gunja'),
            array('zip_code' => '32261','county_id' => 16,'name' => 'Rajevo Selo'),
            array('zip_code' => '32262','county_id' => 16,'name' => 'Račinovci'),
            array('zip_code' => '32263','county_id' => 16,'name' => 'Đurići'),
            array('zip_code' => '32270','county_id' => 16,'name' => 'Županja'),
            array('zip_code' => '32271','county_id' => 16,'name' => 'Rokovci Andrijaševci'),
            array('zip_code' => '32272','county_id' => 16,'name' => 'Cerna'),
            array('zip_code' => '32273','county_id' => 16,'name' => 'Gradište'),
            array('zip_code' => '32274','county_id' => 16,'name' => 'Štitar'),
            array('zip_code' => '32275','county_id' => 16,'name' => 'Bošnjaci'),
            array('zip_code' => '32276','county_id' => 16,'name' => 'Babina Greda'),
            array('zip_code' => '32280','county_id' => 16,'name' => 'Jarmina'),
            array('zip_code' => '32281','county_id' => 16,'name' => 'Ivankovo'),
            array('zip_code' => '32282','county_id' => 16,'name' => 'Retkovci'),
            array('zip_code' => '32283','county_id' => 16,'name' => 'Vođinci'),
            array('zip_code' => '32284','county_id' => 16,'name' => 'Stari Mikanovci'),
            array('zip_code' => '33000','county_id' => 10,'name' => 'Virovitica'),
            array('zip_code' => '33404','county_id' => 10,'name' => 'Špišić Bukovica'),
            array('zip_code' => '33405','county_id' => 10,'name' => 'Pitomača'),
            array('zip_code' => '33406','county_id' => 10,'name' => 'Lukač'),
            array('zip_code' => '33407','county_id' => 10,'name' => 'Gornje Bazje'),
            array('zip_code' => '33410','county_id' => 10,'name' => 'Suhopolje'),
            array('zip_code' => '33411','county_id' => 10,'name' => 'Gradina'),
            array('zip_code' => '33412','county_id' => 10,'name' => 'Cabuna'),
            array('zip_code' => '33507','county_id' => 10,'name' => 'Crnac'),
            array('zip_code' => '33513','county_id' => 10,'name' => 'Zdenci'),
            array('zip_code' => '33514','county_id' => 10,'name' => 'Čačinci'),
            array('zip_code' => '33515','county_id' => 10,'name' => 'Orahovica'),
            array('zip_code' => '33517','county_id' => 10,'name' => 'Mikleuš'),
            array('zip_code' => '33518','county_id' => 10,'name' => 'Nova Bukovica'),
            array('zip_code' => '33520','county_id' => 10,'name' => 'Slatina'),
            array('zip_code' => '33522','county_id' => 10,'name' => 'Voćin'),
            array('zip_code' => '33523','county_id' => 10,'name' => 'Čađavica'),
            array('zip_code' => '33525','county_id' => 10,'name' => 'Sopje'),
            array('zip_code' => '33533','county_id' => 10,'name' => 'Pivnica Slavonska'),
            array('zip_code' => '34000','county_id' => 11,'name' => 'Požega'),
            array('zip_code' => '34308','county_id' => 11,'name' => 'Jakšić'),
            array('zip_code' => '34310','county_id' => 11,'name' => 'Pleternica'),
            array('zip_code' => '34311','county_id' => 11,'name' => 'Kuzmica'),
            array('zip_code' => '34312','county_id' => 11,'name' => 'Sesvete (kod Požege)'),
            array('zip_code' => '34315','county_id' => 11,'name' => 'Ratkovica'),
            array('zip_code' => '34322','county_id' => 11,'name' => 'Brestovac'),
            array('zip_code' => '34330','county_id' => 11,'name' => 'Velika'),
            array('zip_code' => '34334','county_id' => 11,'name' => 'Kaptol'),
            array('zip_code' => '34335','county_id' => 11,'name' => 'Vetovo'),
            array('zip_code' => '34340','county_id' => 11,'name' => 'Kutjevo'),
            array('zip_code' => '34343','county_id' => 11,'name' => 'Bektež'),
            array('zip_code' => '34350','county_id' => 11,'name' => 'Čaglin'),
            array('zip_code' => '34543','county_id' => 11,'name' => 'Poljana'),
            array('zip_code' => '34550','county_id' => 11,'name' => 'Pakrac'),
            array('zip_code' => '34551','county_id' => 11,'name' => 'Lipik'),
            array('zip_code' => '34552','county_id' => 11,'name' => 'Badljevina'),
            array('zip_code' => '34553','county_id' => 11,'name' => 'Bučje'),
            array('zip_code' => '35000','county_id' => 12,'name' => 'Slavonski Brod'),
            array('zip_code' => '35105','county_id' => 12,'name' => 'Slavonski Brod'),
            array('zip_code' => '35106','county_id' => 12,'name' => 'Slavonski Brod'),
            array('zip_code' => '35107','county_id' => 12,'name' => 'Podvinje'),
            array('zip_code' => '35201','county_id' => 12,'name' => 'Podcrkavlje'),
            array('zip_code' => '35207','county_id' => 12,'name' => 'Gornja Vrba'),
            array('zip_code' => '35208','county_id' => 12,'name' => 'Ruščica'),
            array('zip_code' => '35209','county_id' => 12,'name' => 'Bukovlje'),
            array('zip_code' => '35210','county_id' => 12,'name' => 'Vrpolje'),
            array('zip_code' => '35211','county_id' => 12,'name' => 'Trnjani'),
            array('zip_code' => '35212','county_id' => 12,'name' => 'Garčin'),
            array('zip_code' => '35213','county_id' => 12,'name' => 'Oprisavci'),
            array('zip_code' => '35214','county_id' => 12,'name' => 'Donji Andrijevci'),
            array('zip_code' => '35216','county_id' => 12,'name' => 'Prnjavor'),
            array('zip_code' => '35220','county_id' => 12,'name' => 'Slavonski Šamac'),
            array('zip_code' => '35221','county_id' => 12,'name' => 'Velika Kopanica'),
            array('zip_code' => '35222','county_id' => 12,'name' => 'Gundinci'),
            array('zip_code' => '35224','county_id' => 12,'name' => 'Sikirevci'),
            array('zip_code' => '35250','county_id' => 12,'name' => 'Oriovac'),
            array('zip_code' => '35252','county_id' => 12,'name' => 'Sibinj'),
            array('zip_code' => '35253','county_id' => 12,'name' => 'Brodski Stupnik'),
            array('zip_code' => '35254','county_id' => 12,'name' => 'Bebrina'),
            array('zip_code' => '35255','county_id' => 12,'name' => 'Slavonski Kobaš'),
            array('zip_code' => '35257','county_id' => 12,'name' => 'Lužani'),
            array('zip_code' => '35400','county_id' => 12,'name' => 'Nova Gradiška'),
            array('zip_code' => '35403','county_id' => 12,'name' => 'Rešetari'),
            array('zip_code' => '35404','county_id' => 12,'name' => 'Cernik'),
            array('zip_code' => '35410','county_id' => 12,'name' => 'Nova Kapela'),
            array('zip_code' => '35414','county_id' => 12,'name' => 'Vrbova'),
            array('zip_code' => '35420','county_id' => 12,'name' => 'Staro Petrovo Selo'),
            array('zip_code' => '35422','county_id' => 12,'name' => 'Zapolje'),
            array('zip_code' => '35423','county_id' => 12,'name' => 'Vrbje'),
            array('zip_code' => '35424','county_id' => 12,'name' => 'Orubica'),
            array('zip_code' => '35425','county_id' => 12,'name' => 'Davor'),
            array('zip_code' => '35428','county_id' => 12,'name' => 'Dragalić'),
            array('zip_code' => '35429','county_id' => 12,'name' => 'Gornji Bogićevci'),
            array('zip_code' => '35430','county_id' => 12,'name' => 'Okučani'),
            array('zip_code' => '35435','county_id' => 12,'name' => 'Stara Gradiška'),
            array('zip_code' => '40000','county_id' => 20,'name' => 'Čakovec'),
            array('zip_code' => '40305','county_id' => 20,'name' => 'Nedelišće'),
            array('zip_code' => '40306','county_id' => 20,'name' => 'Macinec'),
            array('zip_code' => '40311','county_id' => 20,'name' => 'Lopatinec'),
            array('zip_code' => '40312','county_id' => 20,'name' => 'Štrigova'),
            array('zip_code' => '40313','county_id' => 20,'name' => 'Sveti Martin na Muri'),
            array('zip_code' => '40314','county_id' => 20,'name' => 'Selnica'),
            array('zip_code' => '40315','county_id' => 20,'name' => 'Mursko Središče'),
            array('zip_code' => '40317','county_id' => 20,'name' => 'Podturen'),
            array('zip_code' => '40318','county_id' => 20,'name' => 'Dekanovec'),
            array('zip_code' => '40319','county_id' => 20,'name' => 'Belica'),
            array('zip_code' => '40320','county_id' => 20,'name' => 'Donji Kraljevec'),
            array('zip_code' => '40321','county_id' => 20,'name' => 'Mala Subotica'),
            array('zip_code' => '40322','county_id' => 20,'name' => 'Orehovica'),
            array('zip_code' => '40323','county_id' => 20,'name' => 'Prelog'),
            array('zip_code' => '40324','county_id' => 20,'name' => 'Goričan'),
            array('zip_code' => '40325','county_id' => 20,'name' => 'Draškovec'),
            array('zip_code' => '40326','county_id' => 20,'name' => 'Sveta Marija'),
            array('zip_code' => '40327','county_id' => 20,'name' => 'Donji Vidovec'),
            array('zip_code' => '40328','county_id' => 20,'name' => 'Donja Dubrava'),
            array('zip_code' => '40329','county_id' => 20,'name' => 'Kotoriba'),
            array('zip_code' => '42000','county_id' => 5,'name' => 'Varaždin'),
            array('zip_code' => '42201','county_id' => 5,'name' => 'Beretinec'),
            array('zip_code' => '42202','county_id' => 5,'name' => 'Trnovec Bartolovečki'),
            array('zip_code' => '42203','county_id' => 5,'name' => 'Jalžabet'),
            array('zip_code' => '42204','county_id' => 5,'name' => 'Turčin'),
            array('zip_code' => '42205','county_id' => 5,'name' => 'Vidovec'),
            array('zip_code' => '42206','county_id' => 5,'name' => 'Petrijanec'),
            array('zip_code' => '42207','county_id' => 5,'name' => 'Vinica'),
            array('zip_code' => '42208','county_id' => 5,'name' => 'Cestica'),
            array('zip_code' => '42209','county_id' => 5,'name' => 'Sračinec'),
            array('zip_code' => '42214','county_id' => 5,'name' => 'Sveti Ilija'),
            array('zip_code' => '42220','county_id' => 5,'name' => 'Novi Marof'),
            array('zip_code' => '42222','county_id' => 5,'name' => 'Ljubeščica'),
            array('zip_code' => '42223','county_id' => 5,'name' => 'Varaždinske Toplice'),
            array('zip_code' => '42225','county_id' => 5,'name' => 'Breznički Hum'),
            array('zip_code' => '42230','county_id' => 5,'name' => 'Ludbreg'),
            array('zip_code' => '42231','county_id' => 5,'name' => 'Mali Bukovec'),
            array('zip_code' => '42232','county_id' => 5,'name' => 'Donji Martijanec'),
            array('zip_code' => '42233','county_id' => 5,'name' => 'Sveti Đurđ'),
            array('zip_code' => '42240','county_id' => 5,'name' => 'Ivanec'),
            array('zip_code' => '42242','county_id' => 5,'name' => 'Radovan'),
            array('zip_code' => '42243','county_id' => 5,'name' => 'Maruševec'),
            array('zip_code' => '42244','county_id' => 5,'name' => 'Klenovnik'),
            array('zip_code' => '42245','county_id' => 5,'name' => 'Donja Voća'),
            array('zip_code' => '42250','county_id' => 5,'name' => 'Lepoglava'),
            array('zip_code' => '42253','county_id' => 5,'name' => 'Bednja'),
            array('zip_code' => '42254','county_id' => 5,'name' => 'Trakošćan'),
            array('zip_code' => '42255','county_id' => 5,'name' => 'Donja Višnjica'),
            array('zip_code' => '43000','county_id' => 7,'name' => 'Bjelovar'),
            array('zip_code' => '43202','county_id' => 7,'name' => 'Zrinski Topolovac'),
            array('zip_code' => '43203','county_id' => 7,'name' => 'Kapela'),
            array('zip_code' => '43211','county_id' => 7,'name' => 'Predavac'),
            array('zip_code' => '43212','county_id' => 7,'name' => 'Rovišće'),
            array('zip_code' => '43226','county_id' => 7,'name' => 'Veliko Trojstvo'),
            array('zip_code' => '43227','county_id' => 7,'name' => 'Šandrovac'),
            array('zip_code' => '43231','county_id' => 7,'name' => 'Ivanska'),
            array('zip_code' => '43232','county_id' => 7,'name' => 'Berek'),
            array('zip_code' => '43233','county_id' => 7,'name' => 'Trnovitički Popovac'),
            array('zip_code' => '43240','county_id' => 7,'name' => 'Čazma'),
            array('zip_code' => '43246','county_id' => 7,'name' => 'Štefanje'),
            array('zip_code' => '43247','county_id' => 7,'name' => 'Narta'),
            array('zip_code' => '43251','county_id' => 7,'name' => 'Gudovac'),
            array('zip_code' => '43252','county_id' => 7,'name' => 'Prgomelje'),
            array('zip_code' => '43270','county_id' => 7,'name' => 'Veliki Grđevac'),
            array('zip_code' => '43272','county_id' => 7,'name' => 'Nova Rača'),
            array('zip_code' => '43273','county_id' => 7,'name' => 'Bulinac'),
            array('zip_code' => '43274','county_id' => 7,'name' => 'Severin'),
            array('zip_code' => '43280','county_id' => 7,'name' => 'Garešnica'),
            array('zip_code' => '43282','county_id' => 7,'name' => 'Veliko Vukovje'),
            array('zip_code' => '43283','county_id' => 7,'name' => 'Kaniška Iva'),
            array('zip_code' => '43284','county_id' => 7,'name' => 'Hercegovac'),
            array('zip_code' => '43290','county_id' => 7,'name' => 'Grubišno Polje'),
            array('zip_code' => '43293','county_id' => 7,'name' => 'Veliki Zdenci'),
            array('zip_code' => '43500','county_id' => 7,'name' => 'Daruvar'),
            array('zip_code' => '43505','county_id' => 7,'name' => 'Končanica (Končenice)'),
            array('zip_code' => '43506','county_id' => 7,'name' => 'Dežanovac'),
            array('zip_code' => '43507','county_id' => 7,'name' => 'Uljanik'),
            array('zip_code' => '43531','county_id' => 7,'name' => 'Veliki Bastaji'),
            array('zip_code' => '43532','county_id' => 7,'name' => 'Đulovac'),
            array('zip_code' => '43541','county_id' => 7,'name' => 'Sirač'),
            array('zip_code' => '44000','county_id' => 3,'name' => 'Sisak'),
            array('zip_code' => '44010','county_id' => 3,'name' => 'Sisak-Caprag'),
            array('zip_code' => '44201','county_id' => 3,'name' => 'Martinska Ves'),
            array('zip_code' => '44202','county_id' => 3,'name' => 'Topolovac'),
            array('zip_code' => '44203','county_id' => 3,'name' => 'Gušće'),
            array('zip_code' => '44204','county_id' => 3,'name' => 'Jabukovac'),
            array('zip_code' => '44210','county_id' => 3,'name' => 'Sunja'),
            array('zip_code' => '44211','county_id' => 3,'name' => 'Blinjski Kut'),
            array('zip_code' => '44213','county_id' => 3,'name' => 'Kratečko'),
            array('zip_code' => '44250','county_id' => 3,'name' => 'Petrinja'),
            array('zip_code' => '44253','county_id' => 3,'name' => 'Mošćenica'),
            array('zip_code' => '44272','county_id' => 3,'name' => 'Lekenik'),
            array('zip_code' => '44273','county_id' => 3,'name' => 'Sela'),
            array('zip_code' => '44316','county_id' => 3,'name' => 'Velika Ludina'),
            array('zip_code' => '44317','county_id' => 3,'name' => 'Popovača'),
            array('zip_code' => '44318','county_id' => 3,'name' => 'Voloder'),
            array('zip_code' => '44320','county_id' => 3,'name' => 'Kutina'),
            array('zip_code' => '44321','county_id' => 3,'name' => 'Banova Jaruga'),
            array('zip_code' => '44322','county_id' => 3,'name' => 'Lipovljani'),
            array('zip_code' => '44323','county_id' => 3,'name' => 'Rajić'),
            array('zip_code' => '44324','county_id' => 3,'name' => 'Jasenovac'),
            array('zip_code' => '44325','county_id' => 3,'name' => 'Krapje'),
            array('zip_code' => '44330','county_id' => 3,'name' => 'Novska'),
            array('zip_code' => '44400','county_id' => 3,'name' => 'Glina'),
            array('zip_code' => '44410','county_id' => 3,'name' => 'Gvozd'),
            array('zip_code' => '44415','county_id' => 3,'name' => 'Topusko'),
            array('zip_code' => '44430','county_id' => 3,'name' => 'Hrvatska Kostajnica'),
            array('zip_code' => '44431','county_id' => 3,'name' => 'Donji Kukuruzari'),
            array('zip_code' => '44435','county_id' => 3,'name' => 'Divuša'),
            array('zip_code' => '44440','county_id' => 3,'name' => 'Dvor'),
            array('zip_code' => '44450','county_id' => 3,'name' => 'Hrvatska Dubica'),
            array('zip_code' => '47000','county_id' => 4,'name' => 'Karlovac'),
            array('zip_code' => '47201','county_id' => 4,'name' => 'Draganići'),
            array('zip_code' => '47203','county_id' => 4,'name' => 'Rečica'),
            array('zip_code' => '47204','county_id' => 4,'name' => 'Šišljavić'),
            array('zip_code' => '47206','county_id' => 4,'name' => 'Lasinja'),
            array('zip_code' => '47212','county_id' => 4,'name' => 'Skakavac'),
            array('zip_code' => '47220','county_id' => 4,'name' => 'Vojnić'),
            array('zip_code' => '47222','county_id' => 4,'name' => 'Cetingrad'),
            array('zip_code' => '47240','county_id' => 4,'name' => 'Slunj'),
            array('zip_code' => '47241','county_id' => 4,'name' => 'Cerovac Vukmanički'),
            array('zip_code' => '47242','county_id' => 4,'name' => 'Krnjak'),
            array('zip_code' => '47245','county_id' => 4,'name' => 'Rakovica'),
            array('zip_code' => '47246','county_id' => 4,'name' => 'Drežnik Grad'),
            array('zip_code' => '47250','county_id' => 4,'name' => 'Duga Resa'),
            array('zip_code' => '47251','county_id' => 4,'name' => 'Bosiljevo'),
            array('zip_code' => '47252','county_id' => 4,'name' => 'Barilović'),
            array('zip_code' => '47261','county_id' => 4,'name' => 'Zvečaj'),
            array('zip_code' => '47262','county_id' => 4,'name' => 'Generalski Stol'),
            array('zip_code' => '47264','county_id' => 4,'name' => 'Tounj'),
            array('zip_code' => '47271','county_id' => 4,'name' => 'Netretić'),
            array('zip_code' => '47272','county_id' => 4,'name' => 'Ribnik'),
            array('zip_code' => '47276','county_id' => 4,'name' => 'Žakanje'),
            array('zip_code' => '47280','county_id' => 4,'name' => 'Ozalj'),
            array('zip_code' => '47281','county_id' => 4,'name' => 'Mali Erjavec'),
            array('zip_code' => '47282','county_id' => 4,'name' => 'Kamanje'),
            array('zip_code' => '47283','county_id' => 4,'name' => 'Vivodina'),
            array('zip_code' => '47284','county_id' => 4,'name' => 'Kašt'),
            array('zip_code' => '47285','county_id' => 4,'name' => 'Radatovići'),
            array('zip_code' => '47286','county_id' => 4,'name' => 'Mahično'),
            array('zip_code' => '47300','county_id' => 4,'name' => 'Ogulin'),
            array('zip_code' => '47302','county_id' => 4,'name' => 'Oštarije'),
            array('zip_code' => '47303','county_id' => 4,'name' => 'Josipdol'),
            array('zip_code' => '47304','county_id' => 4,'name' => 'Plaški'),
            array('zip_code' => '47306','county_id' => 4,'name' => 'Saborsko'),
            array('zip_code' => '47307','county_id' => 4,'name' => 'Gornje Zagorje'),
            array('zip_code' => '47313','county_id' => 4,'name' => 'Drežnica'),
            array('zip_code' => '47314','county_id' => 4,'name' => 'Jasenak'),
            array('zip_code' => '48000','county_id' => 6,'name' => 'Koprivnica'),
            array('zip_code' => '48214','county_id' => 6,'name' => 'Sveti Ivan Žabno'),
            array('zip_code' => '48260','county_id' => 6,'name' => 'Križevci'),
            array('zip_code' => '48264','county_id' => 6,'name' => 'Kloštar Vojakovački'),
            array('zip_code' => '48265','county_id' => 6,'name' => 'Raven'),
            array('zip_code' => '48267','county_id' => 6,'name' => 'Orehovec'),
            array('zip_code' => '48268','county_id' => 6,'name' => 'Gornja Rijeka'),
            array('zip_code' => '48269','county_id' => 6,'name' => 'Kalnik'),
            array('zip_code' => '48306','county_id' => 6,'name' => 'Sokolovac'),
            array('zip_code' => '48311','county_id' => 6,'name' => 'Kunovec'),
            array('zip_code' => '48312','county_id' => 6,'name' => 'Rasinja'),
            array('zip_code' => '48314','county_id' => 6,'name' => 'Koprivnički Ivanec'),
            array('zip_code' => '48316','county_id' => 6,'name' => 'Đelekovec'),
            array('zip_code' => '48317','county_id' => 6,'name' => 'Legrad'),
            array('zip_code' => '48321','county_id' => 6,'name' => 'Peteranec'),
            array('zip_code' => '48322','county_id' => 6,'name' => 'Drnje'),
            array('zip_code' => '48323','county_id' => 6,'name' => 'Hlebine'),
            array('zip_code' => '48325','county_id' => 6,'name' => 'Novigrad Podravski'),
            array('zip_code' => '48326','county_id' => 6,'name' => 'Virje'),
            array('zip_code' => '48327','county_id' => 6,'name' => 'Molve'),
            array('zip_code' => '48331','county_id' => 6,'name' => 'Gola'),
            array('zip_code' => '48332','county_id' => 6,'name' => 'Ždala'),
            array('zip_code' => '48350','county_id' => 6,'name' => 'Đurđevac'),
            array('zip_code' => '48355','county_id' => 6,'name' => 'Novo Virje'),
            array('zip_code' => '48356','county_id' => 6,'name' => 'Ferdinandovac'),
            array('zip_code' => '48361','county_id' => 6,'name' => 'Kalinovac'),
            array('zip_code' => '48362','county_id' => 6,'name' => 'Kloštar Podravski'),
            array('zip_code' => '48363','county_id' => 6,'name' => 'Podravske Sesvete'),
            array('zip_code' => '49000','county_id' => 2,'name' => 'Krapina'),
            array('zip_code' => '49210','county_id' => 2,'name' => 'Zabok'),
            array('zip_code' => '49214','county_id' => 2,'name' => 'Veliko Trgovišće'),
            array('zip_code' => '49215','county_id' => 2,'name' => 'Tuhelj'),
            array('zip_code' => '49216','county_id' => 2,'name' => 'Desinić'),
            array('zip_code' => '49217','county_id' => 2,'name' => 'Krapinske Toplice'),
            array('zip_code' => '49218','county_id' => 2,'name' => 'Pregrada'),
            array('zip_code' => '49221','county_id' => 2,'name' => 'Bedekovčina'),
            array('zip_code' => '49222','county_id' => 2,'name' => 'Poznanovec'),
            array('zip_code' => '49223','county_id' => 2,'name' => 'Sveti Križ Začretje'),
            array('zip_code' => '49224','county_id' => 2,'name' => 'Lepajci'),
            array('zip_code' => '49225','county_id' => 2,'name' => 'Đurmanec'),
            array('zip_code' => '49228','county_id' => 2,'name' => 'Brestovec Orehovički'),
            array('zip_code' => '49231','county_id' => 2,'name' => 'Hum na Sutli'),
            array('zip_code' => '49232','county_id' => 2,'name' => 'Radoboj'),
            array('zip_code' => '49233','county_id' => 2,'name' => 'Gornje Jesenje'),
            array('zip_code' => '49234','county_id' => 2,'name' => 'Petrovsko'),
            array('zip_code' => '49240','county_id' => 2,'name' => 'Donja Stubica'),
            array('zip_code' => '49243','county_id' => 2,'name' => 'Oroslavje'),
            array('zip_code' => '49244','county_id' => 2,'name' => 'Stubičke Toplice'),
            array('zip_code' => '49245','county_id' => 2,'name' => 'Gornja Stubica'),
            array('zip_code' => '49246','county_id' => 2,'name' => 'Marija Bistrica'),
            array('zip_code' => '49247','county_id' => 2,'name' => 'Zlatar Bistrica'),
            array('zip_code' => '49250','county_id' => 2,'name' => 'Zlatar'),
            array('zip_code' => '49251','county_id' => 2,'name' => 'Mače'),
            array('zip_code' => '49252','county_id' => 2,'name' => 'Mihovljan'),
            array('zip_code' => '49253','county_id' => 2,'name' => 'Lobor'),
            array('zip_code' => '49254','county_id' => 2,'name' => 'Belec'),
            array('zip_code' => '49255','county_id' => 2,'name' => 'Novi Golubovec'),
            array('zip_code' => '49282','county_id' => 2,'name' => 'Konjščina'),
            array('zip_code' => '49283','county_id' => 2,'name' => 'Hraščina-Trgovišće'),
            array('zip_code' => '49284','county_id' => 2,'name' => 'Budinšćina'),
            array('zip_code' => '49290','county_id' => 2,'name' => 'Klanjec'),
            array('zip_code' => '49294','county_id' => 2,'name' => 'Kraljevec na Sutli'),
            array('zip_code' => '49295','county_id' => 2,'name' => 'Kumrovec'),
            array('zip_code' => '49296','county_id' => 2,'name' => 'Zagorska Sela'),
            array('zip_code' => '51000','county_id' => 8,'name' => 'Rijeka'),
            array('zip_code' => '51211','county_id' => 8,'name' => 'Matulji'),
            array('zip_code' => '51212','county_id' => 8,'name' => 'Vele Mune'),
            array('zip_code' => '51213','county_id' => 8,'name' => 'Jurdani'),
            array('zip_code' => '51214','county_id' => 8,'name' => 'Šapjane'),
            array('zip_code' => '51215','county_id' => 8,'name' => 'Kastav'),
            array('zip_code' => '51216','county_id' => 8,'name' => 'Viškovo'),
            array('zip_code' => '51217','county_id' => 8,'name' => 'Klana'),
            array('zip_code' => '51218','county_id' => 8,'name' => 'Dražice'),
            array('zip_code' => '51221','county_id' => 8,'name' => 'Kostrena'),
            array('zip_code' => '51222','county_id' => 8,'name' => 'Bakar'),
            array('zip_code' => '51223','county_id' => 8,'name' => 'Škrljevo'),
            array('zip_code' => '51224','county_id' => 8,'name' => 'Krasica'),
            array('zip_code' => '51225','county_id' => 8,'name' => 'Praputnjak'),
            array('zip_code' => '51226','county_id' => 8,'name' => 'Hreljin'),
            array('zip_code' => '51227','county_id' => 8,'name' => 'Kukuljanovo'),
            array('zip_code' => '51241','county_id' => 8,'name' => 'Križišće'),
            array('zip_code' => '51242','county_id' => 8,'name' => 'Drivenik'),
            array('zip_code' => '51243','county_id' => 8,'name' => 'Tribalj'),
            array('zip_code' => '51244','county_id' => 8,'name' => 'Grižane'),
            array('zip_code' => '51250','county_id' => 8,'name' => 'Novi Vinodolski'),
            array('zip_code' => '51251','county_id' => 8,'name' => 'Ledenice'),
            array('zip_code' => '51252','county_id' => 8,'name' => 'Klenovica'),
            array('zip_code' => '51253','county_id' => 8,'name' => 'Bribir'),
            array('zip_code' => '51260','county_id' => 8,'name' => 'Crikvenica'),
            array('zip_code' => '51261','county_id' => 8,'name' => 'Bakarac'),
            array('zip_code' => '51262','county_id' => 8,'name' => 'Kraljevica'),
            array('zip_code' => '51263','county_id' => 8,'name' => 'Šmrika'),
            array('zip_code' => '51264','county_id' => 8,'name' => 'Jadranovo'),
            array('zip_code' => '51265','county_id' => 8,'name' => 'Dramalj'),
            array('zip_code' => '51266','county_id' => 8,'name' => 'Selce'),
            array('zip_code' => '51280','county_id' => 8,'name' => 'Rab'),
            array('zip_code' => '51281','county_id' => 8,'name' => 'Lopar'),
            array('zip_code' => '51300','county_id' => 8,'name' => 'Delnice'),
            array('zip_code' => '51301','county_id' => 8,'name' => 'Brod na Kupi'),
            array('zip_code' => '51302','county_id' => 8,'name' => 'Kuželj'),
            array('zip_code' => '51303','county_id' => 8,'name' => 'Plešce'),
            array('zip_code' => '51304','county_id' => 8,'name' => 'Gerovo'),
            array('zip_code' => '51305','county_id' => 8,'name' => 'Tršće'),
            array('zip_code' => '51306','county_id' => 8,'name' => 'Čabar'),
            array('zip_code' => '51307','county_id' => 8,'name' => 'Prezid'),
            array('zip_code' => '51311','county_id' => 8,'name' => 'Skrad'),
            array('zip_code' => '51312','county_id' => 8,'name' => 'Brod Moravice'),
            array('zip_code' => '51313','county_id' => 8,'name' => 'Kupjak'),
            array('zip_code' => '51314','county_id' => 8,'name' => 'Ravna Gora'),
            array('zip_code' => '51315','county_id' => 8,'name' => 'Mrkopalj'),
            array('zip_code' => '51316','county_id' => 8,'name' => 'Lokve'),
            array('zip_code' => '51317','county_id' => 8,'name' => 'Crni Lug'),
            array('zip_code' => '51322','county_id' => 8,'name' => 'Fužine'),
            array('zip_code' => '51323','county_id' => 8,'name' => 'Lič'),
            array('zip_code' => '51324','county_id' => 8,'name' => 'Zlobin'),
            array('zip_code' => '51325','county_id' => 8,'name' => 'Moravice'),
            array('zip_code' => '51326','county_id' => 8,'name' => 'Vrbovsko'),
            array('zip_code' => '51327','county_id' => 8,'name' => 'Gomirje'),
            array('zip_code' => '51328','county_id' => 8,'name' => 'Lukovdol'),
            array('zip_code' => '51329','county_id' => 8,'name' => 'Severin na Kupi'),
            array('zip_code' => '51410','county_id' => 8,'name' => 'Opatija'),
            array('zip_code' => '51414','county_id' => 8,'name' => 'Ičići'),
            array('zip_code' => '51415','county_id' => 8,'name' => 'Lovran'),
            array('zip_code' => '51417','county_id' => 8,'name' => 'Mošćenička Draga'),
            array('zip_code' => '51418','county_id' => 8,'name' => 'Brseč'),
            array('zip_code' => '51500','county_id' => 8,'name' => 'Krk'),
            array('zip_code' => '51511','county_id' => 8,'name' => 'Malinska'),
            array('zip_code' => '51512','county_id' => 8,'name' => 'Njivice'),
            array('zip_code' => '51513','county_id' => 8,'name' => 'Omišalj'),
            array('zip_code' => '51514','county_id' => 8,'name' => 'Dobrinj'),
            array('zip_code' => '51515','county_id' => 8,'name' => 'Šilo'),
            array('zip_code' => '51516','county_id' => 8,'name' => 'Vrbnik'),
            array('zip_code' => '51517','county_id' => 8,'name' => 'Kornić'),
            array('zip_code' => '51521','county_id' => 8,'name' => 'Punat'),
            array('zip_code' => '51522','county_id' => 8,'name' => 'Draga Bašćanska'),
            array('zip_code' => '51523','county_id' => 8,'name' => 'Baška'),
            array('zip_code' => '51550','county_id' => 8,'name' => 'Mali Lošinj'),
            array('zip_code' => '51551','county_id' => 8,'name' => 'Veli Lošinj'),
            array('zip_code' => '51552','county_id' => 8,'name' => 'Ilovik'),
            array('zip_code' => '51554','county_id' => 8,'name' => 'Nerezine'),
            array('zip_code' => '51555','county_id' => 8,'name' => 'Belej'),
            array('zip_code' => '51556','county_id' => 8,'name' => 'Martinšćica'),
            array('zip_code' => '51557','county_id' => 8,'name' => 'Cres'),
            array('zip_code' => '51559','county_id' => 8,'name' => 'Beli'),
            array('zip_code' => '51561','county_id' => 8,'name' => 'Susak'),
            array('zip_code' => '51562','county_id' => 8,'name' => 'Unije'),
            array('zip_code' => '51564','county_id' => 8,'name' => 'Ćunski'),
            array('zip_code' => '52000','county_id' => 18,'name' => 'Pazin'),
            array('zip_code' => '52100','county_id' => 18,'name' => 'Pula (Pola)'),
            array('zip_code' => '52203','county_id' => 18,'name' => 'Medulin'),
            array('zip_code' => '52204','county_id' => 18,'name' => 'Ližnjan (Lisignano)'),
            array('zip_code' => '52206','county_id' => 18,'name' => 'Marčana'),
            array('zip_code' => '52207','county_id' => 18,'name' => 'Barban'),
            array('zip_code' => '52208','county_id' => 18,'name' => 'Krnica'),
            array('zip_code' => '52210','county_id' => 18,'name' => 'Rovinj (Rovigno)'),
            array('zip_code' => '52211','county_id' => 18,'name' => 'Bale (Valle)'),
            array('zip_code' => '52212','county_id' => 18,'name' => 'Fažana (Fasana)'),
            array('zip_code' => '52215','county_id' => 18,'name' => 'Vodnjan (Dignano)'),
            array('zip_code' => '52216','county_id' => 18,'name' => 'Galižana (Gallesano)'),
            array('zip_code' => '52220','county_id' => 18,'name' => 'Labin'),
            array('zip_code' => '52221','county_id' => 18,'name' => 'Rabac'),
            array('zip_code' => '52222','county_id' => 18,'name' => 'Koromačno'),
            array('zip_code' => '52223','county_id' => 18,'name' => 'Raša'),
            array('zip_code' => '52224','county_id' => 18,'name' => 'Trget'),
            array('zip_code' => '52231','county_id' => 18,'name' => 'Nedešćina'),
            array('zip_code' => '52232','county_id' => 18,'name' => 'Kršan'),
            array('zip_code' => '52233','county_id' => 18,'name' => 'Šušnjevica'),
            array('zip_code' => '52234','county_id' => 18,'name' => 'Plomin'),
            array('zip_code' => '52332','county_id' => 18,'name' => 'Pićan'),
            array('zip_code' => '52333','county_id' => 18,'name' => 'Podpićan'),
            array('zip_code' => '52341','county_id' => 18,'name' => 'Žminj'),
            array('zip_code' => '52342','county_id' => 18,'name' => 'Svetvinčenat'),
            array('zip_code' => '52352','county_id' => 18,'name' => 'Kanfanar'),
            array('zip_code' => '52402','county_id' => 18,'name' => 'Cerovlje'),
            array('zip_code' => '52403','county_id' => 18,'name' => 'Gračišće'),
            array('zip_code' => '52404','county_id' => 18,'name' => 'Sveti Petar u šumi'),
            array('zip_code' => '52420','county_id' => 18,'name' => 'Buzet'),
            array('zip_code' => '52422','county_id' => 18,'name' => 'Lanišće'),
            array('zip_code' => '52423','county_id' => 18,'name' => 'Karojba'),
            array('zip_code' => '52424','county_id' => 18,'name' => 'Motovun (Montana)'),
            array('zip_code' => '52425','county_id' => 18,'name' => 'Roč'),
            array('zip_code' => '52426','county_id' => 18,'name' => 'Lupoglav'),
            array('zip_code' => '52427','county_id' => 18,'name' => 'Livade (Levade)'),
            array('zip_code' => '52428','county_id' => 18,'name' => 'Oprtalj (Portole)'),
            array('zip_code' => '52429','county_id' => 18,'name' => 'Grožnjan (Grisignana)'),
            array('zip_code' => '52434','county_id' => 18,'name' => 'Boljun'),
            array('zip_code' => '52440','county_id' => 18,'name' => 'Poreč (Parenzo)'),
            array('zip_code' => '52444','county_id' => 18,'name' => 'Tinjan'),
            array('zip_code' => '52445','county_id' => 18,'name' => 'Baderna'),
            array('zip_code' => '52446','county_id' => 18,'name' => 'Nova Vas'),
            array('zip_code' => '52447','county_id' => 18,'name' => 'Vižinada (Visinada)'),
            array('zip_code' => '52448','county_id' => 18,'name' => 'Sveti Lovreč'),
            array('zip_code' => '52449','county_id' => 18,'name' => 'Červar Porat'),
            array('zip_code' => '52450','county_id' => 18,'name' => 'Vrsar (Orsera)'),
            array('zip_code' => '52452','county_id' => 18,'name' => 'Funtana (Fontane)'),
            array('zip_code' => '52460','county_id' => 18,'name' => 'Buje (Buie)'),
            array('zip_code' => '52462','county_id' => 18,'name' => 'Momjan (Momiano)'),
            array('zip_code' => '52463','county_id' => 18,'name' => 'Višnjan (Visignano)'),
            array('zip_code' => '52464','county_id' => 18,'name' => 'Kaštelir (Castelliere)'),
            array('zip_code' => '52465','county_id' => 18,'name' => 'Tar (Torre)'),
            array('zip_code' => '52466','county_id' => 18,'name' => 'Novigrad (Cittanova)'),
            array('zip_code' => '52470','county_id' => 18,'name' => 'Umag (Umago)'),
            array('zip_code' => '52474','county_id' => 18,'name' => 'Brtonigla (Verteneglio)'),
            array('zip_code' => '52475','county_id' => 18,'name' => 'Savudrija (Salvore)'),
            array('zip_code' => '53000','county_id' => 9,'name' => 'Gospić'),
            array('zip_code' => '53201','county_id' => 9,'name' => 'Lički Osik'),
            array('zip_code' => '53202','county_id' => 9,'name' => 'Perušić'),
            array('zip_code' => '53203','county_id' => 9,'name' => 'Kosinj'),
            array('zip_code' => '53206','county_id' => 9,'name' => 'Brušane'),
            array('zip_code' => '53211','county_id' => 9,'name' => 'Smiljan'),
            array('zip_code' => '53212','county_id' => 9,'name' => 'Klanac'),
            array('zip_code' => '53213','county_id' => 9,'name' => 'Donje Pazarište'),
            array('zip_code' => '53220','county_id' => 9,'name' => 'Otočac'),
            array('zip_code' => '53223','county_id' => 9,'name' => 'Vrhovine'),
            array('zip_code' => '53224','county_id' => 9,'name' => 'Ličko Lešće'),
            array('zip_code' => '53230','county_id' => 9,'name' => 'Korenica'),
            array('zip_code' => '53231','county_id' => 9,'name' => 'Plitvička Jezera'),
            array('zip_code' => '53233','county_id' => 9,'name' => 'Ličko Petrovo Selo'),
            array('zip_code' => '53234','county_id' => 9,'name' => 'Udbina'),
            array('zip_code' => '53236','county_id' => 9,'name' => 'Podlapača'),
            array('zip_code' => '53244','county_id' => 9,'name' => 'Lovinac'),
            array('zip_code' => '53250','county_id' => 9,'name' => 'Donji Lapac'),
            array('zip_code' => '53260','county_id' => 9,'name' => 'Brinje'),
            array('zip_code' => '53261','county_id' => 9,'name' => 'Križpolje'),
            array('zip_code' => '53262','county_id' => 9,'name' => 'Jezerane'),
            array('zip_code' => '53270','county_id' => 9,'name' => 'Senj'),
            array('zip_code' => '53271','county_id' => 9,'name' => 'Krivi Put'),
            array('zip_code' => '53273','county_id' => 9,'name' => 'Vratnik'),
            array('zip_code' => '53274','county_id' => 9,'name' => 'Krasno'),
            array('zip_code' => '53284','county_id' => 9,'name' => 'Sveti Juraj'),
            array('zip_code' => '53287','county_id' => 9,'name' => 'Jablanac'),
            array('zip_code' => '53288','county_id' => 9,'name' => 'Karlobag'),
            array('zip_code' => '53289','county_id' => 9,'name' => 'Lukovo Šugarje'),
            array('zip_code' => '53291','county_id' => 9,'name' => 'Novalja'),
            array('zip_code' => '53294','county_id' => 9,'name' => 'Lun'),
            array('zip_code' => '53296','county_id' => 9,'name' => 'Zubovići'),
        );


        DB::table('cities')->insert($cities);
    }

}


